export const CREATE_CHARACTER = 'CREATE_CHARACTER'
export const MODIFY_CHARACTER = 'MODIFY_CHARACTER'
export const DELETE_CHARACTER = 'DELETE_CHARACTER'

export const CREATE_GAME = 'CREATE_GAME'
export const SELECT_GAME = 'SELECT_GAME'
export const DELETE_GAME = 'DELETE_GAME'

export const SHOW_GAME_LIST = 'SHOW_GAME_LIST'
export const CHANGE_NEW_CHARACTER_NAME = 'CHANGE_NEW_CHARACTER_NAME'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const SHOW_CREATE_CHARACTER_PAGE = 'SHOW_CREATE_CHARACTER_PAGE'

export const LOAD_GAMES = 'LOAD_GAMES'