export const CREATE_CHARACTER = 'CREATE_CHARACTER'
export const MODIFY_CHARACTER = 'MODIFY_CHARACTER'
export const DELETE_CHARACTER = 'DELETE_CHARACTER'

export const CREATE_GAME = 'CREATE_GAME'
export const SELECT_GAME = 'SELECT_GAME'
export const DELETE_GAME = 'DELETE_GAME'

export const SHOW_NEW_GAME_PAGE = 'SHOW_NEW_GAME_PAGE'