export const CREATE_CHARACTER = 'CREATE_CHARACTER'
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER'
export const DELETE_CHARACTER = 'DELETE_CHARACTER'

export const CREATE_GAME = 'CREATE_GAME'
export const SELECT_GAME = 'SELECT_GAME'
export const DELETE_GAME = 'DELETE_GAME'

export const SHOW_GAME_LIST = 'SHOW_GAME_LIST'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const SHOW_GAME_PAGE = 'SHOW_GAME_PAGE'
export const SHOW_CHARACTER_EDIT = 'SHOW_CHARACTER_EDIT'
export const CLOSE_CHARACTER_EDIT = 'CLOSE_CHARACTER_EDIT'

export const LOAD_GAMES = 'LOAD_GAMES'
export const LOAD_CHARACTERS = 'LOAD_CHARACTERS'

export const OPEN_SETTINGS = 'OPEN_SETTINGS'

export const CREATE_RACE = 'CREATE_RACE'
export const INITIALIZE_RACES = 'INITIALIZE_RACES'
